version: "3.4"
services:
  csharp: #docker run -it -v ${PWD}:/work -w /work -p 5000:5000 aimvector/csharp:1.0.0 /bin/sh
    container_name: csharp-aspnet
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    build:
      context: .
      target: debug
    volumes:
    - .:/acb-app/
    ports:
      - 4141:4141